### ISSUE TITLE
HELp

### ISSUE THREAD

**Issue by Unknownio** [hydrox19/discord-music#11]
Error: Cannot find module 'C:\Users\Acer\Desktop\discord-music-master\start'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)       
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by inhydrox** [comment]
Did you installed all the packages?
